// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv5oIn0TEPTA5A7fvLkI8vyxh9vTFE4Fc',
    appId: '1:47662042278:web:ea0f485a0bd13369c7f867',
    messagingSenderId: '47662042278',
    projectId: 'screentranslation-cff83',
    authDomain: 'screentranslation-cff83.firebaseapp.com',
    storageBucket: 'screentranslation-cff83.firebasestorage.app',
    measurementId: 'G-89JB2JVTTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBq6mwB0Kcc9A5AX9SPWvhPgItCo_u4Go',
    appId: '1:47662042278:android:0c6f39c3e4a3b4c0c7f867',
    messagingSenderId: '47662042278',
    projectId: 'screentranslation-cff83',
    storageBucket: 'screentranslation-cff83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYpPhe1Ro-lRvUOyLvPQUk4-NbGJScg_w',
    appId: '1:47662042278:ios:35e84ea6277e5809c7f867',
    messagingSenderId: '47662042278',
    projectId: 'screentranslation-cff83',
    storageBucket: 'screentranslation-cff83.firebasestorage.app',
    iosBundleId: 'com.lomoware.screenTranslate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYpPhe1Ro-lRvUOyLvPQUk4-NbGJScg_w',
    appId: '1:47662042278:ios:35e84ea6277e5809c7f867',
    messagingSenderId: '47662042278',
    projectId: 'screentranslation-cff83',
    storageBucket: 'screentranslation-cff83.firebasestorage.app',
    iosBundleId: 'com.lomoware.screenTranslate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv5oIn0TEPTA5A7fvLkI8vyxh9vTFE4Fc',
    appId: '1:47662042278:web:db00a1d99a0479e3c7f867',
    messagingSenderId: '47662042278',
    projectId: 'screentranslation-cff83',
    authDomain: 'screentranslation-cff83.firebaseapp.com',
    storageBucket: 'screentranslation-cff83.firebasestorage.app',
    measurementId: 'G-SBR5QRVVRG',
  );

}